[package]
name = "reconstruction"
version = "0.1.0"
authors = ["Zaheer Chothia <zchothia@inf.ethz.ch>"]

[dependencies]
abomonation = "0.5"
abomonation_derive = "0.3"
rand = "0.4"
timely = "0.5"
redis = "*"
serde = {version = "1.0", features = ["derive"] }
serde_json = "*"
uuid = { version = "0.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
