[package]
name = "pythia"
version = "0.1.0"
authors = ["Emre Ates <ates@bu.edu>"]
default-run = "pythia"

[dependencies]
redis = "*"
serde = {version = "1.0", features = ["derive"] }
serde_json = "*"
uuid = { version = "0.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
petgraph = { version = "0.4.13", features = ["serde-1"] }
clap = "*"
config = "*"
rust-crypto = "*"
streaming-stats = "*"
lazy_static = "1.4.0"
indexmap = "*"
