[package]
name = "pythia"
version = "0.1.0"
authors = ["Emre Ates <ates@bu.edu>"]
default-run = "pythia"
edition = "2018"

[dependencies]
redis = "*"
serde = {version = "1.0", features = ["derive"] }
serde_json = "*"
rand = "0.7"
uuid = { version = "0.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
petgraph = { version = "0.5.0", features = ["serde-1"] }
clap = "*"
config = "*"
rust-crypto = "*"
streaming-stats = "*"
lazy_static = "1.4.0"
indexmap = "*"
typetag = "0.1.4"
jsonrpc-core = "*"
jsonrpc-core-client = "*"
jsonrpc-client-transports = "*"
hyper = "0.12"
jsonrpc-derive = "*"
jsonrpc-http-server = "*"
futures = "~0.1.6"
dirs = "*"
regex = "*"
