server_address = "127.0.0.1:3030"

pythia_cache = "/opt/stack/pythia_cache"
manifest_root = "/opt/stack/manifest"

redis_url = "redis://localhost:6379"

manifest_method = "Flat" # can be CCT, Poset, Historic, Flat
