server_address = "0.0.0.0:3030"

pythia_cache = "/opt/stack/pythia_cache"
manifest_root = "/opt/stack/manifest"

redis_url = "redis://localhost:6379"

pythia_clients = "http://localhost:3030,http://cp-1:3030"

manifest_method = "Flat" # can be CCT, Poset, Historic, Flat
