#application = "OpenStack" # can be HDFS, OpenStack, Uber, DEATHSTAR, Zipkin, Jaeger
application = "Jaeger" # can be HDFS, OpenStack, Uber, DEATHSTAR, Zipkin, Jaeger
search_strategy = "Hierarchical" # can be Flat, Hierarchical, Historic

manifest_file = "/opt/stack/manifest.json"
redis_url = "redis://localhost:6379"
xtrace_url = "http://localhost:4080"
uber_trace_dir = "/Users/merttoslali/Desktop/ec900/denemeHDFS/recons/deathstar-traces/compose/individual" # Change to where the Uber traces are
DEATHSTAR_trace_dir = "/Users/merttoslali/Desktop/ec900/denemeHDFS/recons/deathstar-traces/compose/individual" # Change to where the Uber traces are
hdfs_control_file = "/local/hdfs/tracing-framework/pythia.txt"
zipkin_url="http://localhost:16686"
jaeger_url="http://localhost:16686"

# Split by commas, of the form http://localhost:3030
pythia_clients = "http://ctl:3030,http://cp-1:3030"

# other settings are defined in src/settings.rs

# aux settings:
emit_events = "false"

# Expected problematic endpoint/request type
problem_type = "ServerCreate"


