application = "OpenStack" # can be HDFS, OpenStack, Uber
search_strategy = "Flat" # can be Flat

manifest_file = "/opt/stack/manifest.json"
redis_url = "redis://localhost:6379"
xtrace_url = "http://localhost:4080"

# Split by commas, of the form http://localhost:3030
pythia_clients = "http://localhost:3030,http://cp-1:3030"
